
export const GET_PROJECT = 'app/ModifyProjectPage/GET_PROJECT';
export const GET_PROJECT_SUCCESS = 'app/ModifyProjectPage/GET_PROJECT_SUCCESS';
export const GET_PROJECT_ERROR = 'app/ModifyProjectPage/GET_PROJECT_ERROR';

export const POST_PROJECT_MODIFICATION = 'app/ModifyProjectPage/POST_PROJECT_MODIFICATION';
export const POST_PROJECT_MODIFICATION_SUCCESS = 'app/ModifyProjectPage/POST_PROJECT_MODIFICATION_SUCCESS';
export const POST_PROJECT_MODIFICATION_ERROR = 'app/ModifyProjectPage/POST_PROJECT_MODIFICATION_ERROR';
